export {
  augmentCardWithQuickAgentGroups,
  buildQuickAgentGroupCapability,
  buildQuickAgentGroupCapabilityId,
  cardSupportsQuickAgentGroup,
  createQuickAgentGroupInvite,
  createQuickAgentGroupManager,
  createQuickAgentGroupMessageRouter,
  discoverQuickAgentGroupMembers,
  extractQuickAgentGroupIds,
  generateQuickAgentGroupId,
  isQuickAgentGroupInviteExpired,
  validateQuickAgentGroupId,
  validateQuickAgentGroupInvite,
  verifyQuickAgentGroupInvite,
  type CreateQuickAgentGroupInviteInput,
  type QuickAgentGroupDiscoveryScope,
  type QuickAgentGroupInvite,
  type QuickAgentGroupInviteMetadata,
  type QuickAgentGroupManager,
  type QuickAgentGroupMembership,
} from '@quadra-a/protocol';
